// Smooth scrolling effect for menu links
document.addEventListener('DOMContentLoaded', function() {
  const menuLinks = document.querySelectorAll('.menu a');

  menuLinks.forEach(link => {
    link.addEventListener('click', function(event) {
      event.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      const headerOffset = 100;
      const elementPosition = target.getBoundingClientRect().top;
      const offsetPosition = elementPosition - headerOffset;

      window.scrollBy({
        top: offsetPosition,
        behavior: 'smooth'
      });
    });
  });
});

function openModal(comicId) {
      var modal = document.getElementById("modal");
      var comicTitle = document.getElementById("comic-title-modal");
      var comicReview = document.getElementById("comic-review-modal");

      // Set the modal content based on the comicId
      if (comicId === "blood+") {
        comicTitle.textContent = "Blood +";
        comicReview.innerHTML = "<i>Saya Otonashi</i> is a seemingly ordinary girl living a mundane life with her adoptive family in Okinawa City. In fact, her only peculiarities are suffering from anemia and being unable to remember any of her life beyond the previous year. <br> However, Saya's forgotten past quickly comes back to haunt her—one night, she is attacked at school by a creature that feeds on human blood. <br>Just when all hope seems lost, a mysterious man named <i>Haji</i> appears and fends off the creature temporarily. But when her rescuer forces her to drink his blood,Saya suddenly enters a trance and slays the monster with ease, using her own blood as a catalyst.<br> Saya then learns of an organization named Red Shield, founded for the sole purpose of defeating the hellish beasts. Now Saya and Haji must work together with Red Shield to fight these fearsome monsters and unlock the secrets to the girl's past.";
      } else if (comicId === "bleach") {
        comicTitle.textContent = "Bleach";
        comicReview.innerHTML = "<i>Ichigo Kurosaki</i> is an ordinary high schooler—until his family is attacked by a <i>Hollow</i>, a corrupt spirit that seeks to devour human souls. It is then that he meets a Soul Reaper named <i>Rukia Kuchiki</i>, who gets injured while protecting Ichigo's family from the assailant. <br> To save his family, Ichigo accepts Rukia's offer of taking her powers and becomes a Soul Reaper as a result. However, as Rukia is unable to regain her powers, Ichigo is given the daunting task of hunting down the Hollows that plague their town. <br>However, he is not alone in his fight, as he is later joined by his friends—classmates <i>Orihime Inoue</i>, <i>Yasutora Sado</i>, and <i>Uryuu Ishida</i> — who each have their own unique abilities. <br>As Ichigo and his comrades get used to their new duties and support each other on and off the battlefield, the young Soul Reaper soon learns that the Hollows are not the only real threat to the human world.";
      }
      else if (comicId === "dbz") {
        comicTitle.textContent = "DragonballZ";
        comicReview.innerHTML = "Five years after winning the World Martial Arts tournament, <i>SON-Goku</i> is now living a peaceful life with his wife and son. This changes, however, with the arrival of a mysterious enemy named <i>Raditz</i> who presents himself as Goku's long-lost brother. He reveals that Goku is a warrior from the once powerful but now virtually extinct Saiyan race, whose homeworld was completely annihilated.<br> When he was sent to Earth as a baby, Goku's sole purpose was to conquer and destroy the planet; but after suffering amnesia from a head injury, his violent and savage nature changed, and instead was raised as a kind and well-mannered boy, now fighting to protect others. <br>With his failed attempt at forcibly recruiting Goku as an ally, Raditz warns Goku's friends of a new threat that's rapidly approaching Earth—one that could plunge Earth into an intergalactic conflict and cause the heavens themselves to shake. <br>A war will be fought over the seven mystical dragon balls, and only the strongest will survive in Dragon Ball Z. ";
      }
  else if (comicId === "naruto") {
        comicTitle.textContent = "DragonballZ";
        comicReview.innerHTML = "Moments prior to <i>Naruto Uzumaki</i>'s birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the <i>Hidden Leaf Village</i>, and wreaked havoc. <br>In order to put an end to the Kyuubi's rampage, the leader of the village, the Fourth Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. <br>Now, Naruto is a hyperactive and knuckle-headed ninja still living in Konohagakure. <br>Shunned because of the Kyuubi inside him, Naruto struggles to find his place in the village, while his burning desire to become the Hokage of Konohagakure leads him not only to some great new friends, but also some deadly foes. ";
      }
   else if (comicId === "narutoS") {
        comicTitle.textContent = "Naruto Shippudden";
        comicReview.innerHTML = "It has been two and a half years since Naruto Uzumaki left Konohagakure, the Hidden Leaf Village, for intense training following events which fueled his desire to be stronger. <br>Now <i>Akatsuki</i>, the mysterious organization of elite rogue ninja, is closing in on their grand plan which may threaten the safety of the entire shinobi world. <br>Although Naruto is older and sinister events loom on the horizon, he has changed little in personality—still rambunctious and childish—though he is now far more confident and possesses an even greater determination to protect his friends and home. <br>Come whatever may, Naruto will carry on with the fight for what is important to him, even at the expense of his own body, in the continuation of the saga about the boy who wishes to become Hokage. <br> This anime is so much more, and is not given justice by  few lines here. Give this anime a watch and figure out for yourself what truth really is, and if there really are winners in war?? ";
      }
  else if (comicId === "samuraichamp") {
        comicTitle.textContent = "Samurai Champloo";
        comicReview.innerHTML = "<i>Fuu Kasumi</i> is a young and clumsy waitress who spends her days peacefully working in a small teahouse. That is, until she accidentally spills a drink all over one of her customers! With a group of samurai now incessantly harassing her, <i>Fuu</i> desperately calls upon another samurai in the shop, <i>Mugen</i>, who quickly defeats them with his wild fighting technique, utilizing movements reminiscent to that of breakdancing. <br>Unfortunately, Mugen decides to pick a fight with the unwilling ronin <i>Jin</i>, who wields a more precise and traditional style of swordfighting, and the latter proves to be a formidable opponent. The only problem is, they end up destroying the entire shop as well as accidentally killing the local magistrate's son. For their crime, the two samurai are captured and set to be executed. However, they are rescued by Fuu, who hires the duo as her bodyguards. <br>Though she no longer has a place to return to, the former waitress wishes to find a certain samurai who smells of sunflowers and enlists the help of the now exonerated pair to do so. Despite initially disapproving of this idea, the two eventually agree to assist the girl in her quest; thus, the trio embark upon an adventure to find this mysterious warrior—that is, if Fuu can keep Mugen and Jin from killing each other. <br>Set in an alternate Edo Period of Japan, Samurai Champloo follows the journey of these three eccentric individuals in an epic quest full of action, comedy, and dynamic sword fighting, all set to the beat of a unique hip-hop infused soundtrack. ";
      } 
 else if (comicId === "afrosamurai") {
        comicTitle.textContent = "Afro Samurai";
        comicReview.innerHTML = "When he was a young boy, <i>Afro</i> witnessed his father be cut down in a duel at the hands of a man known only as <i>Justice</i>. After taking the life of Afro's father, Justice cast aside his </i>Number Two headband</i> and took the Number One to claim its godly powers as his own. <br>Years later, having obtained the Number Two headband which grants him the right to challenge the Number One, Afro moves forward in his hunt for revenge on the man who murdered his father. <br>There is just one thing that stands in his way—everyone else in the world! Though the Number One can only be challenged by the Number Two, the Number Two can be challenged by anyone. As his enemies gather to try and take the title of Number Two, Afro must fight through a myriad of foes and obstacles if he hopes to reach the Number One and claim vengeance once and for all.";
      } 
   else if (comicId === "fatestaynight") {
        comicTitle.textContent = "Fate/Stay Night";
        comicReview.innerHTML = "After a mysterious inferno kills his family, <i>Shirou</i> is saved and adopted by Kiritsugu Emiya, who teaches him the ways of magic and justice. One night, years after Kiritsugu's death, Shirou is cleaning at school, when he finds himself caught in the middle of a deadly encounter between two superhumans known as Servants. <br>During his attempt to escape, the boy is caught by one of the Servants and receives a life-threatening injury. Miraculously, he survives, but the same Servant returns to finish what he started. In desperation, Shirou summons a Servant of his own, a knight named <i>Saber</i>. <br>The two must now participate in the Fifth Holy Grail War, a battle royale of seven Servants and the mages who summoned them, with the grand prize being none other than the omnipotent Holy Grail itself. <br>Fate/stay night follows Shirou as he struggles to find the fine line between a hero and a killer, his ideals clashing with the harsh reality around him. Will the boy become a hero like his foster father, or die trying";
      }
  else if (comicId === "xxxholic") {
        comicTitle.textContent = "XXXHolic";
        comicReview.innerHTML = "<i>Kimihiro Watanuki</i> can see spirits and other assorted supernatural creatures, which is quite a bothersome ability he strongly dislikes. On the way home one day, while plagued by some spirits, he is inexplicably compelled to enter a strange house. There, he encounters <i>Yuuko</i>, a mysterious woman who claims to be able to rid him of the ability to see and attract the troublesome creatures—for a price. She demands that he work at her <i>store</i> that grants wishes to people, and thus begins Watanuki's adventures through weird and wonderful events.";
      }
  else if (comicId === "devilman") {
        comicTitle.textContent = "Devilman: Crybaby";
        comicReview.innerHTML = "Devils cannot take form without a living host. However, if the will of an individual is strong enough, they can overcome the demon and make its power their own, becoming a Devilman. <br> Weak and unassuming, <i>Akira Fudou</i> has always had a bleeding heart. So when his childhood friend Ryou Asuka asks for his help in uncovering devils, Akira accepts without hesitation. However, to Akira's surprise, the place they go to is Sabbath: an immoral party of debauchery and degeneracy. <br>Amidst bloodshed and death, demons possess the partiers, turning their bodies into grotesque monsters, and begin wreaking havoc. In a reckless attempt to save his best friend, Akira unwittingly merges with the devil <i>Amon</i> and becomes a Devilman, gaining the power to defeat the remaining demons. <br>Though it grants him great power, this new partnership awakens an insatiable and primeval part of Akira. Having the body of a devil but the same crybaby heart, Akira works alongside Ryou, destroying those that harm humanity and his loved ones";
      }
  else if (comicId === "deathnote") {
        comicTitle.textContent = "Death Note";
        comicReview.innerHTML = "A <i>shinigami</i>, as a god of death, can kill any person—provided they see their victim's face and write their victim's name in a notebook called a <i>Death Note</i>. One day, <i>Ryuk</i>, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm. <br>High school student and prodigy <i>Light Yagami</i> stumbles upon the Death Note and—since he deplores the state of the world—tests the deadly notebook by writing a criminal's name in it. When the criminal dies immediately following his experiment with the Death Note, Light is greatly surprised and quickly recognizes how devastating the power that has fallen into his hands could be. <br>With this divine capability, Light decides to extinguish all criminals in order to build a new world where crime does not exist and people worship him as a god. <br>Police, however, quickly discover that a serial killer is targeting criminals and, consequently, try to apprehend the culprit. To do this, the Japanese investigators count on the assistance of the best detective in the world: a young and eccentric man known only by the name of <i>L</i>.";
      }
   else if (comicId === "neon-genesis") {
        comicTitle.textContent = "Neon Genesis Evangelion";
        comicReview.innerHTML = "In the year 2015, the world stands on the brink of destruction. Humanity's last hope lies in the hands of Nerv, a special agency under the United Nations, and their Evangelions, giant machines capable of defeating the Angels who herald Earth's ruin. <i>Gendou Ikari</i>, head of the organization, seeks compatible pilots who can synchronize with the Evangelions and realize their true potential. <br>Aiding in this defensive endeavor are talented personnel <i>Misato Katsuragi</i>, Head of Tactical Operations, and Ritsuko Akagi, Chief Scientist. Face to face with his father for the first time in years, 14-year-old <i>Shinji Ikari</i>'s average life is irreversibly changed when he is whisked away into the depths of Nerv, and into a harrowing new destiny—he must become the pilot of <i>Evangelion Unit-01</i> with the fate of mankind on his shoulders. <br>Neon Genesis Evangelion is a heroic tale of a young boy who will become a legend. But as this psychological drama unfolds, ancient secrets beneath the big picture begin to bubble to the surface.";
      } 
  else if (comicId === "ghostintheshell") {
        comicTitle.textContent = "Ghost in the Shell: Stand Alone Complex";
        comicReview.innerHTML = "In the not so distant future, mankind has advanced to a state where complete body transplants from flesh to machine is possible. <br>This allows for great increases in both physical and cybernetic prowess and blurring the lines between the two worlds. However, criminals can also make full use of such technology, leading to new and sometimes, very dangerous crimes. <br>In response to such innovative new methods, the Japanese Government has established <i>Section 9</i>, an independently operating police unit which deals with such highly sensitive crimes. Led by <i>Daisuke Aramaki</i> and <i>Motoko Kusanagi</i>, Section 9 deals with such crimes over the entire social spectrum, usually with success. <br>However, when faced with a new A level hacker nicknamed <i>The Laughing Man</i>, the team is thrown into a dangerous cat and mouse game, following the hacker's trail as it leaves its mark on Japan.";
      }
  else if (comicId === "pokemon") {
        comicTitle.textContent = "Pokemon";
        comicReview.innerHTML = "Pokemon are peculiar creatures with a vast array of different abilities and appearances; many people, known as Pokemon trainers, capture and train them, often with the intent of battling others. Young </i>Ash</i> has not only dreamed of becoming a Pokemon trainer but also a <i>Pokemon Master</i>, and on the arrival of his 10th birthday, he finally has a chance to make that dream a reality.<br>Unfortunately for him, all three Pokemon available to beginning trainers have already been claimed and only Pikachu, a rebellious Electric type Pokemon, remains. <br>However, this chance encounter would mark the start of a lifelong friendship and an epic adventure! Setting off on a journey to become the very best, Satoshi and Pikachu travel across beautiful, sprawling regions with their friends Kasumi, a Water type trainer, and Takeshi, a Rock type trainer. <br>But danger lurks around every corner. The infamous <i>Team Rocket</i> is always nearby, seeking to steal powerful Pokemon through nefarious schemes. It'll be up to Satoshi and his friends to thwart their efforts as he also strives to earn the eight Pokemon Gym Badges he'll need to challenge the Pokemon League, and eventually claim the title of Pokemon Master.";
      }
  else if (comicId === "psychopass") {
        comicTitle.textContent = "Psycho-Pass";
        comicReview.innerHTML = "Justice, and the enforcement of it, has changed. In the 22nd century, Japan enforces the <i>Sibyl System</i>, an objective means of determining the threat level of each citizen by examining their mental state for signs of criminal intent, known as their Psycho-Pass. <br>Inspectors uphold the law by subjugating, often with lethal force, anyone harboring the slightest ill-will; alongside them are Enforcers, jaded Inspectors that have become latent criminals, granted relative freedom in exchange for carrying out the Inspectors' dirty work. <br>Into this world steps <i>Akane Tsunemori</i>, a young woman with an honest desire to uphold justice. <br>However, as she works alongside veteran Enforcer <i>Shinya Kougami</i>, she soon learns that the Sibyl System's judgments are not as perfect as her fellow Inspectors assume. <br>With everything she has known turned on its head, Akane wrestles with the question of what justice truly is, and whether it can be upheld through the use of a system that may already be corrupt. ";
      }
  else if (comicId === "haruhi") {
        comicTitle.textContent = "The Melancholy Of Haruhi Suzumiya";
        comicReview.innerHTML = "<i>Kyon</i>, your typical high school student, has long given up his belief in the supernatural. However, upon meeting <i>Haruhi Suzumiya</i>, he quickly finds out that it is the supernatural that she is interested in—aliens, time travelers, and espers among other things. <br>When Haruhi laments about the lack of intriguing clubs around school, Kyon inspires Haruhi to form her own club. <br>As a result, the SOS Brigade is formed, a club which specializes in all that is the supernatural. Much to his chagrin, Kyon, along with the silent bookworm, Yuki Nagato, the shy and timid Mikuru Asahina, and the perpetually smiling Itsuki Koizumi, are recruited as members. <br>The story follows the crazy adventures that these four endure under their whimsical leader, Haruhi. The story is based on the light novels by Nagaru Tanigawa.";
      }
  else if (comicId === "dbsuper") {
        comicTitle.textContent = "Dragon Ball Super";
        comicReview.innerHTML = "Seven years after the events of Dragon Ball Z, Earth is at peace, and its people live free from any dangers lurking in the universe. However, this peace is short-lived; a sleeping evil awakens in the dark reaches of the galaxy: <i>Beerus</i>, the ruthless <i>God of Destruction</i>. Disturbed by a prophecy that he will be defeated by a <i>Super Saiyan God</i>, Beerus and his angelic attendant <i>Whis</i> start searching the universe for this mysterious being. <br>Before long, they reach Earth where they encounter SON-Goku, one of the planet's mightiest warriors, and his similarly powerful friends. <br>The concepts introduced in the latter of the series is a really interesting take on the power system of <i>Super Saiyans</i>, and changed my personal overview of the power heirarchy of the characters in the Dragon Bakk universe.";
      }
  else if (comicId === "AOT") {
        comicTitle.textContent = "Attack on Titan";
        comicReview.innerHTML = "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. <br>To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations. <br>After witnessing a horrific personal loss at the hands of the invading creatures, <i>Eren Yeager</i> dedicates his life to their eradication by enlisting into the <i>Survey Corps</i>, an elite military unit that combats the merciless humanoids outside the protection of the walls. <br><i>Shingeki no Kyojin</i> follows Eren, along with his adopted sister <i>Mikasa Ackerman</i> and his childhood friend <i>Armin Arlert</i>, as they join the brutal war against the titans and race to discover a way of defeating them before the last walls are breached. ";
      }
  else if (comicId === "blackbutler") {
        comicTitle.textContent = "Black Butler";
        comicReview.innerHTML = "Young <i>Ciel Phantomhive</i> is known as the <i>Queen's Guard Dog</i>, taking care of the many unsettling events that occur in Victorian England for Her Majesty. <br>Aided by <i>Sebastian Michaelis</i>, his loyal butler with seemingly inhuman abilities, Ciel uses whatever means necessary to get the job done. <br>But is there more to this black-clad butler than meets the eye? In Ciel's past lies a secret tragedy that enveloped him in perennial darkness—during one of his bleakest moments, he formed a contract with Sebastian, a demon, bargaining his soul in exchange for vengeance upon those who wronged him. <br>Today, not only is Sebastian one hell of a butler, but he is also the perfect servant to carry out his master's orders—all the while anticipating the delicious meal he will eventually make of Ciel's soul. As the two work to unravel the mystery behind Ciel's chain of misfortunes, a bond forms between them that neither heaven nor hell can tear apart. <br> Personally, Sebastian stole the show and was the main attraction for me to watch this series. An interesting perspective on the Master-Servant idealogy!! ";
      }
  else if (comicId === "chainsawman") {
        comicTitle.textContent = "Chainsaw Man";
        comicReview.innerHTML = "<i>Denji</i> is robbed of a normal teenage life, left with nothing but his deadbeat father's overwhelming debt. His only companion is his pet, the chainsaw devil <i>Pochita</i>, with whom he slays devils for money that inevitably ends up in the yakuza's pockets. <br>All Denji can do is dream of a good, simple life: one with delicious food and a beautiful girlfriend by his side. But an act of greedy betrayal by the yakuza leads to Denji's brutal, untimely death, crushing all hope of him ever achieving happiness. Remarkably, an old contract allows Pochita to merge with the deceased Denji and bestow devil powers on him, changing him into a hybrid able to transform his body parts into chainsaws. <<br>Because Denji's new abilities pose a significant risk to society, the Public Safety Bureau's elite devil hunter <i>Makima</i> takes him in, letting him live as long as he obeys her command. <br>Guided by the promise of a content life alongside an attractive woman, Denji devotes everything and fights with all his might to make his naive dreams a reality. Another interesting perspective put into existence by the beauty of MAPPA studios";
      }
  else if (comicId === "demonslayer") {
        comicTitle.textContent = "Demon Slayer: Kimetsu no Yaiba";
        comicReview.innerHTML = "Ever since the death of his father, the burden of supporting the family has fallen upon </i>Tanjirou Kamado</i>'s shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life. <br>One day, Tanjirou decides to go down to the local village to make a little money selling charcoal. On his way back, night falls, forcing Tanjirou to take shelter in the house of a strange man, who warns him of the existence of flesh-eating demons that lurk in the woods at night. <br>When he finally arrives back home the next day, he is met with a horrifying sight—his whole family has been slaughtered. Worse still, the sole survivor is his sister <i>Nezuko</i>, who has been turned into a bloodthirsty demon. <br>Consumed by rage and hatred, Tanjirou swears to avenge his family and stay by his only remaining sibling. Alongside the mysterious group calling themselves the <i>Demon Slayer Corps</i>, Tanjirou will do whatever it takes to slay the demons and protect the remnants of his beloved sister's humanity.";
      }
  else if (comicId === "fma") {
        comicTitle.textContent = "Fullmetal Alchemist: Brotherhood";
        comicReview.innerHTML = "<i>In order for something to be obtained, something of equal value must be lost.</i><br>Alchemy is bound by this Law of Equivalent Exchange—something the young brothers <i>Edward</i> and <i>Alphonse Elric</i> only realize after attempting <i>human transmutation</i>: the one forbidden act of alchemy. <br>They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward's right arm that he is able to affix Alphonse's soul to a suit of armor. <br>Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called automail and become a state alchemist, <i>the Fullmetal Alchemist</i>. <br>Three years of searching later, the brothers seek the <i>Philosopher's Stone</i>, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. <br>Even with military allies <i>Colonel Roy Mustang</i>, <i>Lieutenant Riza Hawkeye</i>, and <i>Lieutenant Colonel Maes Hughes</i> on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher's Stone, but their country's murky history as well.<br> This anime was one of my first watches, and man did it leave an impact on me. Another anime where the whole story come full circle on itself, delving into philosophical aspects of life and death!! A must watch!!";
      }
  else if (comicId === "cowboybebop") {
        comicTitle.textContent = "Cowboy Bebop";
        comicReview.innerHTML = "In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as <i>Cowboys</i>.<br> The ragtag team aboard the spaceship Bebop are two such individuals. Mellow and carefree <i>Spike Spiegel</i> is balanced by his boisterous, pragmatic partner <i>Jet Black</i> as the pair makes a living chasing bounties and collecting rewards. <br>Thrown off course by the addition of new members that they meet in their travels—Ein, a genetically engineered, highly intelligent <i>Welsh Corgi</i>; femme fatale <i>Faye Valentine</i>, an enigmatic trickster with memory loss; and the strange computer whiz kid <i>Edward Wong</i>—the crew embarks on thrilling adventures that unravel each member's dark and mysterious past little by little.<br> Well-balanced with high density action and light-hearted comedy, Cowboy Bebop is a timeless space Western classic and an homage to the smooth and improvised music it is named after. <br> One of my personal favorites";
      }
  else if (comicId === "gurren") {
        comicTitle.textContent = "Gurren Lagann";
        comicReview.innerHTML = "<i>Simon</i> and <i>Kamina</i> were born and raised in a deep, underground village, hidden from the fabled surface. <br>Kamina is a free-spirited loose cannon bent on making a name for himself, while Simon is a timid young boy with no real aspirations. <br>One day while excavating the earth, Simon stumbles upon a mysterious object that turns out to be the ignition key to an ancient artifact of war, which the duo dubs Lagann. Using their new weapon, Simon and Kamina fend off a surprise attack from the surface with the help of <i>Yoko Littner</i>, a hot-blooded redhead wielding a massive gun who wanders the world above. <br>In the aftermath of the battle, the sky is now in plain view, prompting Simon and Kamina to set off on a journey alongside Yoko to explore the wastelands of the surface. Soon, they join the fight against the <i>Beastmen</i>, humanoid creatures that terrorize the remnants of humanity in powerful robots called <i>Gunmen</i>. <br>Although they face some challenges and setbacks, the trio bravely fights these new enemies alongside other survivors to reclaim the surface, while slowly unraveling a galaxy-sized mystery.";
      }
  else if (comicId === "ghoul") {
        comicTitle.textContent = "Tokyo Ghoul";
        comicReview.innerHTML = "Tokyo has become a cruel and merciless city—a place where vicious creatures called <i>ghouls</i> exist alongside humans. <br>The citizens of this once great metropolis live in constant fear of these bloodthirsty savages and their thirst for human flesh. However, the greatest threat these ghouls pose is their dangerous ability to masquerade as humans and blend in with society.<br> Based on the best-selling supernatural horror manga by Sui Ishida, Tokyo Ghoul follows <i>Ken Kaneki</i>, a shy, bookish college student, who is instantly drawn to <i>Rize Kamishiro</i>, an avid reader like himself. <br>However, Rize is not exactly who she seems, and this unfortunate meeting pushes Kaneki into the dark depths of the ghouls' inhuman world. <br>In a twist of fate, Kaneki is saved by the enigmatic waitress Touka Kirishima, and thus begins his new, secret life as a half-ghoul/half-human who must find a way to integrate into both societies.";
      }
  else if (comicId === "akira") {
        comicTitle.textContent = "Akira";
        comicReview.innerHTML = "Japan, 1988. An explosion caused by a young boy with psychic powers tears through the city of Tokyo and ignites the fuse that leads to World War III. In order to prevent any further destruction, he is captured and taken into custody, never to be heard from again. <br>Now, in the year 2019, a restored version of the city known as Neo-Tokyo—an area rife with gang violence and terrorism against the current government—stands in its place. <br>Here, <i>Shoutarou Kaneda</i> leads <i>the Capsules</i>, a group of misfits known for riding large, custom motorcycles and being in constant conflict with their rivals the Clowns. During one of these battles, Shoutarou's best friend <i>Tetsuo Shima</i> is caught up in an accident with an esper who finds himself in the streets of Tokyo after escaping confinement from a government institution. <br>Through this encounter, Tetsuo begins to develop his own mysterious abilities, as the government seeks to quarantine this latest psychic in a desperate attempt to prevent him from unleashing the destructive power that could once again bring the city to its knees. A timeless classic which paved the way for future anime to come!! A must watch movie!!";
      }
else if (comicId === "ergo") {
        comicTitle.textContent = "Ergo Proxy";
        comicReview.innerHTML = "Within the domed city of Romdo lies one of the last human civilizations on Earth. Thousands of years ago, a global ecological catastrophe doomed the planet; now, life outside these domes is virtually impossible. <br>To expedite mankind's recovery, <i>AutoReivs</i>, humanoid-like robots, have been created to assist people in their day-to-day lives.<br> However, AutoReivs have begun contracting an enigmatic disease called the <i>Cogito Virus</i> which grants them self-awareness.<br> Re-l Mayer, granddaughter of Romdo's ruler, is assigned to investigate this phenomenon alongside her AutoReiv partner <i>Iggy</i>. <br>But what begins as a routine investigation quickly spirals into a conspiracy as Re-l is confronted by humanity's darkest sins. <br>Elsewhere in Romdo, an AutoReiv specialist by the name of <i>Vincent Law</i> must also face his demons when surreal events begin occurring around him. Re-l, Iggy, Vincent, and the child AutoReiv named Pino, will form an unlikely faction as they struggle to uncover Romdo's mysteries and ultimately, discover the true purpose of the mythical beings called ,<i>Proxies</i>.";
      }
  else if (comicId === "steinsgate") {
        comicTitle.textContent = "Steins;Gate";
        comicReview.innerHTML = "The self-proclaimed mad scientist <i>Rintarou Okabe</i> rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective future gadgets with fellow lab members: <i>Mayuri Shiina</i>, his air-headed childhood friend, and <i>Hashida Itaru</i>, a perverted hacker nicknamed <i>Daru</i>. <br>The three pass the time by tinkering with their most promising contraption yet, a machine dubbed the ,<i>Phone Microwave</i>, which performs the strange function of morphing bananas into piles of green gel. <br>Though miraculous in itself, the phenomenon doesn't provide anything concrete in Okabe's search for a scientific breakthrough; that is, until the lab members are spurred into action by a string of mysterious happenings before stumbling upon an unexpected success—the Phone Microwave can send emails to the past, altering the flow of history. <br>Steins;Gate takes Okabe through the depths of scientific theory and practicality. Forced across the diverging threads of past and present, Okabe must shoulder the burdens that come with holding the key to the realm of time. A great anime to watch if time exploration is your thing!!";
      }
  else if (comicId === "geass") {
        comicTitle.textContent = "Code Geass: Lelouch of the Rebellion";
        comicReview.innerHTML = "In the year 2010, the Holy Empire of Britannia is establishing itself as a dominant military nation, starting with the conquest of Japan. Renamed to <i>Area 11</i> after its swift defeat, Japan has seen significant resistance against these tyrants in an attempt to regain independence. <br><i>Lelouch Lamperouge</i>, a Britannian student, unfortunately finds himself caught in a crossfire between the Britannian and the Area 11 rebel armed forces. <br>He is able to escape, however, thanks to the timely appearance of a mysterious girl named <i>C.C</i>., who bestows upon him <i>Geass</i>, the <i>Power of Kings</i>. <br>Realizing the vast potential of his newfound power of absolute obedience, Lelouch embarks upon a perilous journey as the masked vigilante known as <i>Zero</i>, leading a merciless onslaught against Britannia in order to get revenge once and for all. ";
      }
  else if (comicId === "revengers") {
        comicTitle.textContent = "Tokyo Revengers";
        comicReview.innerHTML = "<i>Takemichi Hanagaki</i>'s life is at an all-time low. <br>Just when he thought it couldn't get worse, he finds out that <i>Hinata Tachibana</i>, his ex-girlfriend, was murdered by the <i>Tokyo Manji Gang</i>: a group of vicious criminals that has been disturbing society's peace for quite some time.<br> Wondering where it all went wrong, Takemichi suddenly finds himself travelling through time, ending up 12 years in the past—when he was still in a relationship with Hinata. <br>Realizing he has a chance to save her, Takemichi resolves to infiltrate the Tokyo Manji Gang and climb the ranks in order to rewrite the future and save Hinata from her tragic fate. If you like gang wars in a school with a time-travel twist, this is your next watch!! ";
      }
  else if (comicId === "bleachwararc") {
        comicTitle.textContent = "Bleach: Thousand-Year Blood War Arc";
        comicReview.innerHTML = "Substitute Soul Reaper <i>Ichigo Kurosaki</i> spends his days fighting against Hollows, dangerous evil spirits that threaten Karakura Town.<br> Ichigo carries out his quest with his closest allies: <i>Orihime Inoue</i>, his childhood friend with a talent for healing; <i>Yasutora Sado</i>, his high school classmate with superhuman strength; and <i>Uryuu Ishida</i>, Ichigo's Quincy rival. <br>Ichigo's vigilante routine is disrupted by the sudden appearance of <i>Asguiaro Ebern</i>, a dangerous Arrancar who heralds the return of <i>Yhwach</i>, an ancient Quincy king.<br> Yhwach seeks to reignite the historic blood feud between Soul Reaper and Quincy, and he sets his sights on erasing both the human world and the Soul Society for good. <br>Yhwach launches a two-pronged invasion into both the Soul Society and Hueco Mundo, the home of Hollows and Arrancar. In retaliation, Ichigo and his friends must fight alongside old allies and enemies alike to end Yhwach's campaign of carnage before the world itself comes to an end ";
      }
  modal.style.display = "block";
}

function closeModal() {
      var modal = document.getElementById("modal");
      modal.style.display = "none";
    }

//Filter Option
// JavaScript to filter anime based on selected rating
  document.getElementById("rating-filter").addEventListener("change", function() {
    const selectedRating = this.value;
    const animeList = document.querySelectorAll(".comic-card");

    animeList.forEach(anime => {
      const rating = anime.getAttribute("data-rating");

      if (selectedRating === "all" || rating === selectedRating) {
        anime.style.display = "block";
      } else {
        anime.style.display = "none";
      }
    });
  });
